//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonModels.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonModels.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AUTORESIZE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AUTORESIZE {
            get {
                return ResourceManager.GetString("AUTORESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COPY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EDIT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EVENT TEST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EVENTTEST {
            get {
                return ResourceManager.GetString("EVENTTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FILE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOGWRITE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LOGWRITE {
            get {
                return ResourceManager.GetString("LOGWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M1MENU1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M1MENU1 {
            get {
                return ResourceManager.GetString("M1MENU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M1MENU2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M1MENU2 {
            get {
                return ResourceManager.GetString("M1MENU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M2MENU1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M2MENU1 {
            get {
                return ResourceManager.GetString("M2MENU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M2MENU2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M2MENU2 {
            get {
                return ResourceManager.GetString("M2MENU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M9MENU1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M9MENU1 {
            get {
                return ResourceManager.GetString("M9MENU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M9MENU2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string M9MENU2 {
            get {
                return ResourceManager.GetString("M9MENU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MODULE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MODULE {
            get {
                return ResourceManager.GetString("MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   READ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string READ {
            get {
                return ResourceManager.GetString("READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RESET に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRISM WPF SAMPLE  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LANGUAGE SETTING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM1 {
            get {
                return ResourceManager.GetString("TITLEM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PRISM EXPLANATION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM2 {
            get {
                return ResourceManager.GetString("TITLEM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM3 {
            get {
                return ResourceManager.GetString("TITLEM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OXYPLOT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM4 {
            get {
                return ResourceManager.GetString("TITLEM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETTING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM5 {
            get {
                return ResourceManager.GetString("TITLEM5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONVERTER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM6 {
            get {
                return ResourceManager.GetString("TITLEM6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SAVE WINDOW POSITION に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM7 {
            get {
                return ResourceManager.GetString("TITLEM7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NO DOUBLE BOOT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM8 {
            get {
                return ResourceManager.GetString("TITLEM8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MENU に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEM9 {
            get {
                return ResourceManager.GetString("TITLEM9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BEHAVIOR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TITLEMA {
            get {
                return ResourceManager.GetString("TITLEMA", resourceCulture);
            }
        }
    }
}
